{% set name = "vt-py" %}
{% set version = "0.17.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vt-py-{{ version }}.tar.gz
  sha256: 2f96fe86c7213dda9e45ab06bf18f7843f9513c1a073b1606fe238ea624a5b32

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - aiohttp
    - python >=3.6

test:
  imports:
    - vt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.virustotal.com/gui/
  summary: The official Python client library for VirusTotal
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://virustotal.github.io/vt-py/
  doc_url: https://github.com/VirusTotal/vt-py

extra:
  recipe-maintainers:
    - BastianZim
